name: Build and Publish Binaries

on:
  workflow_dispatch:
    inputs:
      version_number:
        required: true
        default: "0.0.1"
        description: "Version number for this release"
        type: string

jobs:
  build:
    runs-on: "windows-latest"

    steps:

      - name: Gettin' Started
        run: |
          echo currently running {{ $runner.os }} {{ $runner.arch }}
          echo github ref is currently {{ $github.ref }}
          echo github.version_number is currently {{ $github.version_number }}

      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Installing lilbinboy itself, for dependencies and to bake in version info from setuptools-scm
      - name: Install Dependencies
        run: |
          pip install .

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          product-version: ${{ github.event.inputs.version_number }}
          file-version: ${{ github.version_number }}
          macos-app-version: ${{ github.version_number }}
          output-dir: build
          script-name: main.py
          mode: app
      
      - name: Move Dist Files Into Place
        run: |
          mkdir dist
          move build/lilbinboy.exe dist/lilbinboy_{{ $runner.os }}_{{ $runner.arch }}_{{ $github.version_number}}.exe 

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.0
        with: dist/*