on:
  workflow_dispatch:
    inputs:
      version_number:
        required: true
        default: "v0.0.1"
        description: "Version number for this release"
        type: string

  release:
    types:
      - created

jobs:

  # Interpret semver tag info (v1.0.2-pre-release.001) for Windows versioning
  version-info:
    runs-on: ubuntu-latest

    outputs:
      semver:  ${{ steps.regex-match.outputs.group1 }}
      classic: ${{ steps.regex-match.outputs.group2 }}
      build_name: ${{ steps.regex-match.outputs.group3 }}
      full_version: ${{ steps.regex-match.outputs.match }}

    steps:

      - name: Determine version source
        id: determine-version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.version_number }}" != "" ]; then
            echo "version=${{ github.event.inputs.version_number }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "Version number not provided and not triggered by release." >&2
            exit 1
          fi

      - name: Parse semver with regex
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.determine-version.outputs.version }}
          regex: "^v(((?:[0-9]+\\.)*(?:[0-9]+))-?(.*))$"

      - name: Results
        run: |
          echo "Semver:       ${{ steps.regex-match.outputs.group1 }}"
          echo "Classic:      ${{ steps.regex-match.outputs.group2 }}"
          echo "Build Name:   ${{ steps.regex-match.outputs.group3 }}"
          echo "Full Version: ${{ steps.regex-match.outputs.match }}"